/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PEGAZUSGUI.view;

/**
 *
 * @author Rodrigo Soria
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        PerimeterofPlot = new javax.swing.JMenuItem();
        AreaofSurface = new javax.swing.JMenuItem();
        magnitude = new javax.swing.JMenuItem();
        CalculateAceleration = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        TransformTemperature = new javax.swing.JMenuItem();
        WeightofRock = new javax.swing.JMenuItem();
        RiverDisplacment = new javax.swing.JMenuItem();
        Deformation1 = new javax.swing.JMenuItem();
        OilonSite = new javax.swing.JMenuItem();
        EXIT = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        jMenu1.setText("PEGAZUS");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        PerimeterofPlot.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        PerimeterofPlot.setText("Perimeter of Plot");
        PerimeterofPlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerimeterofPlotActionPerformed(evt);
            }
        });
        jMenu1.add(PerimeterofPlot);

        AreaofSurface.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AreaofSurface.setText("Area Of Surface");
        AreaofSurface.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaofSurfaceActionPerformed(evt);
            }
        });
        jMenu1.add(AreaofSurface);

        magnitude.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        magnitude.setText("Magnitude of an Earthquake");
        magnitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magnitudeActionPerformed(evt);
            }
        });
        jMenu1.add(magnitude);

        CalculateAceleration.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        CalculateAceleration.setText("Calculate Aceleration");
        CalculateAceleration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateAcelerationActionPerformed(evt);
            }
        });
        jMenu1.add(CalculateAceleration);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Wave Range");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        TransformTemperature.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        TransformTemperature.setText("Transform Temperature");
        TransformTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransformTemperatureActionPerformed(evt);
            }
        });
        jMenu1.add(TransformTemperature);

        WeightofRock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        WeightofRock.setText("Weight of a Rock");
        WeightofRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightofRockActionPerformed(evt);
            }
        });
        jMenu1.add(WeightofRock);

        RiverDisplacment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        RiverDisplacment.setText("River Displacement");
        RiverDisplacment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiverDisplacmentActionPerformed(evt);
            }
        });
        jMenu1.add(RiverDisplacment);

        Deformation1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Deformation1.setText("Deformation");
        Deformation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Deformation1ActionPerformed(evt);
            }
        });
        jMenu1.add(Deformation1);

        OilonSite.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        OilonSite.setText("Calculate Oil on Site");
        OilonSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OilonSiteActionPerformed(evt);
            }
        });
        jMenu1.add(OilonSite);

        jMenuBar1.add(jMenu1);

        EXIT.setText("Exit");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem3.setText("EXIT");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        EXIT.add(jMenuItem3);

        jMenuBar1.add(EXIT);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerimeterofPlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerimeterofPlotActionPerformed
        PerimeterofPlot window = new PerimeterofPlot ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_PerimeterofPlotActionPerformed

    private void AreaofSurfaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaofSurfaceActionPerformed
       AreaofSurface window = new  AreaofSurface ();
        desktop.add(window);
        window.show(); 
    }//GEN-LAST:event_AreaofSurfaceActionPerformed

    private void magnitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magnitudeActionPerformed
        MagnitudeofEarthquake window = new  MagnitudeofEarthquake ();
        desktop.add(window);
        window.show(); 
    }//GEN-LAST:event_magnitudeActionPerformed

    private void CalculateAcelerationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateAcelerationActionPerformed
      CalculateAceleration window = new  CalculateAceleration ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_CalculateAcelerationActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      WaveRange window = new  WaveRange ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TransformTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransformTemperatureActionPerformed
     TransformTemperature window = new  TransformTemperature ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_TransformTemperatureActionPerformed

    private void WeightofRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightofRockActionPerformed
     WeightofRock window = new  WeightofRock ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_WeightofRockActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
   System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
 
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void RiverDisplacmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiverDisplacmentActionPerformed
     RiverDisplacement window = new  RiverDisplacement ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_RiverDisplacmentActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void Deformation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Deformation1ActionPerformed
      Deformation window = new  Deformation ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_Deformation1ActionPerformed

    private void OilonSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OilonSiteActionPerformed
       CalculatePOE window = new  CalculatePOE  ();
        desktop.add(window);
        window.show();
    }//GEN-LAST:event_OilonSiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AreaofSurface;
    private javax.swing.JMenuItem CalculateAceleration;
    private javax.swing.JMenuItem Deformation1;
    private javax.swing.JMenu EXIT;
    private javax.swing.JMenuItem OilonSite;
    private javax.swing.JMenuItem PerimeterofPlot;
    private javax.swing.JMenuItem RiverDisplacment;
    private javax.swing.JMenuItem TransformTemperature;
    private javax.swing.JMenuItem WeightofRock;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem magnitude;
    // End of variables declaration//GEN-END:variables
}
